name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout code
      uses: actions/checkout@v2

    # ... other steps ...

      
    - name: Run a script from the repository
      run: |
        # Specify the path to your script file here
        chmod +x sahi1258/saturday/tree/master
