name: Every Repo Workflow

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run a script from the repository
      run: |
        # Specify the path to your script file here
        chmod +x sahi1258/saturday/tree/master
